// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Model.Queue = {
    ClassMethods: {
      enqueue: function() {}
    },
    enqueue: function() {}
  };

  module.exports = Tower.Model.Queue;

}).call(this);
