require './store/fileSystem'
#require './store/cassandra'
#require './store/couchdb'
require './store/mongodb'
#require './store/neo4j'
#require './store/postgresql'
#require './store/riak'
#require './store/redis'
