// Generated by CoffeeScript 1.3.1
(function() {

  Tower.HTTP.Route.PolymorphicUrls = {
    ClassMethods: {
      polymorphicUrl: function() {}
    }
  };

  module.exports = Tower.HTTP.Route.PolymorphicUrls;

}).call(this);
