// Generated by CoffeeScript 1.3.1
(function() {
  var File;

  File = require('pathfinder').File;

  Tower.Middleware.Dependencies = function(request, response, next) {
    if (next) {
      return next();
    }
  };

  module.exports = Tower.Middleware.Dependencies;

}).call(this);
