// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Controller.Authentication = {
    ClassMethods: {
      authenticated: function(options) {
        if (options == null) {
          options = {};
        }
      }
    }
  };

}).call(this);
