Tower.Packager.create('tower')
    .server()
        .add('server.js')
        .deps([
            'tower-watch',
            'tower-ready',
            'tower-application'
            ])
    .client()
        .add('client.js');