Tower.Packager.create('tower')
    .server()
        .add('server.js')
        .deps([
            'server/wonder',
            'tower-application',
            'tower-command',
            'tower-router'
            ])
    .client()
        .add('client.js');