// Generated by CoffeeScript 1.3.1
(function() {

  module.exports = {
    errors: {
      missingCallback: "You must pass a callback to %s.",
      missingOption: "You must pass in the '%s' option to %s.",
      notFound: "%s not found.",
      store: {
        missingAttribute: "Missing %s in %s for '%s'"
      },
      asset: {
        notFound: "Asset not found: '%s'\n  Lookup paths: [\n%s\n  ]"
      }
    }
  };

}).call(this);
