// Generated by CoffeeScript 1.3.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

Tower.HTTP.Test.Request = (function(_super) {

  __extends(Request, _super);

  Request.name = 'Request';

  function Request() {
    return Request.__super__.constructor.apply(this, arguments);
  }

  return Request;

})(Tower.HTTP.Request);
