// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Model.MassAssigment = {
    ClassMethods: {
      "protected": function() {},
      accessible: function() {}
    }
  };

  module.exports = Tower.Model.MassAssigment;

}).call(this);
