// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Controller.Caching = {
    freshWhen: function() {},
    stale: function() {},
    expiresIn: function() {}
  };

  module.exports = Tower.Controller.Caching;

}).call(this);
