// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Controller.Sockets = {
    broadcast: function() {},
    emit: function() {},
    connect: function() {}
  };

  module.exports = Tower.Controller.Sockets;

}).call(this);
