// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Support.File = Tower.File = {
    isFile: function() {},
    isDirectory: function() {},
    files: function() {},
    directories: function() {},
    glob: function() {},
    stat: function() {},
    mkdir: function(directory, recursive, callback) {}
  };

  module.exports = Tower.Support.File;

}).call(this);
