// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Support.Number = {
    isInt: function(n) {
      return n === +n && n === (n | 0);
    },
    isFloat: function(n) {
      return n === +n && n !== (n | 0);
    }
  };

  module.exports = Tower.Support.Number;

}).call(this);
