// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Support.RegExp = {
    regexpEscape: function(string) {
      return string.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");
    }
  };

  module.exports = Tower.Support.RegExp;

}).call(this);
