// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Mailer.Configuration = {
    ClassMethods: {
      lib: function() {
        return require('mailer');
      }
    }
  };

  module.exports = Tower.Mailer.Configuration;

}).call(this);
