// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Store.Memory.Calculations = {
    average: function(conditions, options, callback) {},
    sum: function(conditions, options, callback) {},
    min: function(conditions, options, callback) {},
    max: function(conditions, options, callback) {}
  };

  module.exports = Tower.Store.Memory.Calculations;

}).call(this);
