// Generated by CoffeeScript 1.3.1
(function() {

  Tower.Middleware = {};

  require('./middleware/agent');

  require('./middleware/cookies');

  require('./middleware/location');

  require('./middleware/router');

  module.exports = Tower.Middleware;

}).call(this);
